### ISSUE TITLE
Every log slot shows twice

### ISSUE THREAD

**Issue by Calzern** [evansloan/collectionlog.net#101]
**What are you experiencing, describe the bug**
The website shows every item in my log twice. The ingame command also shows every item twice. This only applies to one of my played accounts.

Example screenshots https://i.imgur.com/4M9GPmC.png https://i.imgur.com/iHQh1dG.png

**How are you expecting it would work?**
I assume every item in the log should show only once. 

**What is your username?**
Jerncal (I play other accounts at the same time if that could affect this, Calzts, Calzern)

**Comment by evansloan** [comment]
This has been fixed. Sorry for the delay.
