### ISSUE TITLE
Two accounts showing up

### ISSUE THREAD

**Issue by Jenna961** [evansloan/collectionlog.net#15]
My hardcore (Je nna) is being displayed twice: One that was updated around June 9th, and the other that has been updated recently to this day. The one with 491/1404 is correct and when I look up my name is keeps showing the old log. I have tried everything I could to try and fix this but it doesn't seem to want to update. If there is any way you can delete the old one, or both and I'll just start over that would be great thank you!

**Comment by evansloan** [comment]
Should be fixed now.
