### ISSUE TITLE
Account shows up on hiscores but not when I search it

### ISSUE THREAD

**Issue by mmm-food** [evansloan/collectionlog.net#18]
![image](https://user-images.githubusercontent.com/115184347/194395987-b33d564b-77dd-4e29-803b-1ea7a76eb9b5.png)
![image](https://user-images.githubusercontent.com/115184347/194396004-1aaeefd2-4e83-46ef-a928-0a7d547fd72d.png)

**Comment by evansloan** [comment]
You're searching for MMM FOOD. The account that shows on the hiscores is MMM F00D with zeroes
