### ISSUE TITLE
Changing log slots does not correctly clear kill count summaries

### ISSUE THREAD

**Issue by BearsOnABus** [evansloan/collectionlog.net#2]
![image](https://user-images.githubusercontent.com/97892675/166065333-74a746ba-f1bf-435c-8d92-57355b62d35d.png)

**Comment by evansloan** [comment]
Went through and cleaned up your collection log data. Not sure how many duplicates got uploaded but it should be good now. I'll keep the issue open for now incase this happens again.

**Comment by richpenguin** [comment]
I have the exact same issue as above IGN "karl btw" mines showing 5 lots of every slot

**Comment by evansloan** [comment]
Added some checks to see if a collection log already has an update in progress to prevent conflicting updates that result in dupes [here](https://github.com/evansloan/collection-log-api/commit/89450ea9f086dda065fa46afc1ecb80e851dfada)
