### ISSUE TITLE
Uniques are no longer counted (0/0)

### ISSUE THREAD

**Issue by IromTypo** [evansloan/collectionlog.net#29]
When I sent the log command in my clanchat today, it suddenly said 0/0 uniques. I reset my collection log data a couple of times and re-uploaded it, but it's not working. Even in the collection log screen the unique log slot counter stays at 0/0 when collecting data.

**Comment by IromTypo** [comment]
Ign Amother Typo

**Comment by evansloan** [comment]
Looks like this has fixed itself. For future reference, if you find that your unique counts aren't updating properly, open the log in game, close it, and open it again. There's a bug in the plugin where it can't get the counts properly on first log open. There's a fix in review currently. I'll close this issue when that fix is approved.
