### ISSUE TITLE
Bugged for new users?

### ISSUE THREAD

**Issue by FrankMFJones** [evansloan/collectionlog.net#34]
**Describe the bug**
I click on all the logs it tells me to, but still doesn't allow me to finish because of Callisto, Vettion and Venenatis logs are not shown, even though they have been changed to Venenatis and Spindel etc instead.

**What is your username?**
FrankMFJones

**Comment by evansloan** [comment]
Fixed in https://github.com/evansloan/collection-log/pull/30
