### ISSUE TITLE
coll log plugin showing 3 of everything

### ISSUE THREAD

**Issue by everettcotter** [evansloan/collectionlog.net#4]
i tried uploading my data to the website last night. i think because it wasn't working immediately, i hit the upload button several times.
now it shows 3x of every item in the coll log, and triples the total number of slots per boss.
see: https://i.imgur.com/ChroHek.png
also, when i click through multiple bosses, it does this: https://i.imgur.com/UZjWlaP.png
it also shows triple of everything in the chat commands. see: https://i.imgur.com/znN0szC.png

i've reset the data and tried again, i've deleted the coll log folder and tried again, i've deleted the entire plugin+the coll log folder and tried, nothing will fix it

**Comment by evansloan** [comment]
Added some checks to see if a collection log already has an update in progress to prevent conflicting updates that result in dupes [here](https://github.com/evansloan/collection-log-api/commit/89450ea9f086dda065fa46afc1ecb80e851dfada)
