### ISSUE TITLE
Indicator when new collection log items have been added to the game

### ISSUE THREAD

**Issue by kspanier2013** [evansloan/collectionlog.net#44]
**Describe the solution you'd like**
Currently, when new collection log items are added to the game, there isn't any indicator that collection data needs to be re-uploaded.

Add a new indicator on the user log screen when the user's total unique count is less than the expected total number of unique items.

**Additional context**
Getting the total expected unique count would be the crux of this. Perhaps we could create a new API endpoint for retrieving the highest total unique items from the dataset we have? So at the launch of a new item, the notice would not appear, but as soon as someone uploads their collection log data, it would be updated for everyone. I expect it would be pretty quick, given the plugin's usage.

Example mockup:

![image](https://user-images.githubusercontent.com/10370516/228711948-af8f37f1-b973-43ed-a73b-4fbcce324033.png)

Could appear on a line above the indicator for out-of-sync items from #43, if both apply.

**Comment by evansloan** [comment]
> Getting the total expected unique count would be the crux of this. Perhaps we could create a new API endpoint for retrieving the highest total unique items from the dataset we have?

For simplicity's sake, I wouldn't be against hard coding something like this. The number doesn't change *too* often, and there's generally an inkling of when there's going to be new items added. That way we can avoid the overhead of an API call just to get a static number.
