### ISSUE TITLE
Total obtained does not match specific items collected. Please re-upload collection log data.

### ISSUE THREAD

**Issue by gnarlynacho** [evansloan/collectionlog.net#55]
**What are you experiencing, describe the bug**
Please provide a clear and concise description so triage will be easier. Provide screenshots of the bug if applicable.
"Total obtained does not match specific items collected. Please re-upload collection log data." on website, even after resetting, recalculating, reuploading etc.
**How are you expecting it would work?**
Please provide a clear and concise description what your expectation is. This provides a better context for the bug.
Ideally the website would update the coll log slots and not tell me it does not match (i dont know how to word this without sounding rude, sorry)
**What is your username?**
Please supply your in-game username if applicable.
gnarly nacho

**Comment by kspanier2013** [comment]
So, the intent of the message is to indicate that there's missing data for some specific items. The plugin (currently) is only able to grab the total unique item count (as shown on your account as the 833/1443), and any items on pages that you've iterated through with the plugin open. If you were to add all of the unique items listed under your account on the website, it wouldn't add to 833, and that's where the message comes from.

I believe @evansloan is working on an update to the plugin that will mitigate this, but until then, there isn't a catch-all solution.

Perhaps it's worthwhile to add something to the FAQ (and link to it from the message) in the meanwhile?

**Comment by gnarlynacho** [comment]
Thank you for the response, I appreciate it. I'm imagining it's brought on by me getting coll log slots on other clients (mobile). Something in the FAQ would be useful, although I mainly reported just incase nobody else had this issue yet. Again, thank you for everything you guys do :)

**Comment by Sharpienero** [comment]
@gnarlynacho If you open it in RL and iterate through each page it'll correct it.

**Comment by gnarlynacho** [comment]
Awesome, have heard loads of good things in my cc about the recent updates :)
