### ISSUE TITLE
Double Entries in collection log page

### ISSUE THREAD

**Issue by birdclaws** [evansloan/collectionlog.net#59]
**What are you experiencing, describe the bug**
my collection log, both on the website and in game using log command is showing double. for example, for DKS it shows every drop twice in the log.

![image](https://user-images.githubusercontent.com/130928043/232334182-205dee4d-1612-4364-a398-40d72e3b2290.png)

**How are you expecting it would work?**
Should only show one of each unique item.

**What is your username?**
Txlon

**Comment by evansloan** [comment]
Sorry for the delay. This has been fixed.
