### ISSUE TITLE
Wildy bosses bugged

### ISSUE THREAD

**Issue by ZebGasm** [evansloan/collectionlog.net#62]
**What are you experiencing, describe the bug**
Please provide a clear and concise description so triage will be easier. Provide screenshots of the bug if applicable.

the old wildy boss collection log is still there 

**How are you expecting it would work?**
Please provide a clear and concise description what your expectation is. This provides a better context for the bug.

https://i.imgur.com/6p2zT8o.png

**What is your username?**
Please supply your in-game username if applicable.

**Comment by Marstead** [comment]
Confirming I'm also experiencing the issue. It seems to be because the Collection Log has relabeled the Wildy bosses ("Vet'ion & Calvar'ion") so the plugin is unable to sync those.

**Comment by evansloan** [comment]
Fixed in https://github.com/evansloan/collection-log/pull/30
