### ISSUE TITLE
Use ISO 8601 format for dates

### ISSUE THREAD

**Issue by Breina** [evansloan/collectionlog.net#63]
**Describe the feature**

The current date is displayed as MDY. Users have to deduce this by looking which numbers can be bigger than 12.

Date formats are very ambiguous throughout the world:

![image](https://user-images.githubusercontent.com/3009914/234846251-6b62441d-cd1c-49f3-897d-7ea440838b4c.png)

This issue has been solved in 1988 by [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

**What value provides this feature?**

Using ISO 8601 has many advantages, the most important one being that it's unambiguous.

**Comment by evansloan** [comment]
Fixed here https://github.com/evansloan/collectionlog.net/commit/febe6603917b2abd5501084d9e4ef9b34e3e77ab

User's location will now be factored in when formatting dates

**Comment by Breina** [comment]
Thanks for the quick turnaround!
