### ISSUE TITLE
Number of bosses killed is the same at every boss for some players.

### ISSUE THREAD

**Issue by Explomis** [evansloan/collectionlog.net#66]
**What are you experiencing, describe the bug**
I was scrolling trough a couple of users boss kills, and saw it was all the same. 

**How are you expecting it would work?**
It looks like the boss count comes for every boss comes from the first boss (Abyssal Sire). Normally it would get the right amount of kills for every boss.

**What is your username?**
Explomis

 
![Schermafbeelding 2023-05-01 om 09 53 07](https://user-images.githubusercontent.com/39992975/235425653-75eebfa7-cac0-4c01-97be-9ef0f7c6eb4a.png)
![Schermafbeelding 2023-05-01 om 09 52 57](https://user-images.githubusercontent.com/39992975/235425655-e7287b2f-2b81-4d40-a6f0-ff08752d0b58.png)

**Comment by evansloan** [comment]
Thanks for reporting. A fix is in progress https://github.com/evansloan/collection-log/pull/32

**Comment by evansloan** [comment]
This issue has been resolved. Please click through your collection log to update the site with the correct kill count amounts.
