### ISSUE TITLE
Desyncing of collection log on restart

### ISSUE THREAD

**Issue by EwwItsMike** [evansloan/collectionlog.net#67]
**What are you experiencing, describe the bug**
Please provide a clear and concise description so triage will be easier. Provide screenshots of the bug if applicable.

I'm not entirely sure if it's on RuneLite restart or PC restart, but lately every time I open my collection log for the first time of the day, every single page has an asterisk behind it, and none of the logs that I have completed are greened anymore. 
If I relog my account, this also gets updated on the website and my whole collection log gets cleared from there.

**How are you expecting it would work?**
Please provide a clear and concise description what your expectation is. This provides a better context for the bug.

Plugin should probably either locally store the current progress towards the collection log and load that on startup, or pull the information from the website before being able to send an update to it. It's getting a bit old to have to go through my entire collection log every morning.

**What is your username?**
Please supply your in-game username if applicable.

Ew Its Mike

Some pictures:
![image](https://user-images.githubusercontent.com/120571801/235690896-5e68fb2f-cf73-47f0-a6fe-63365ac5f281.png)
![image](https://user-images.githubusercontent.com/120571801/235690946-7822c050-d201-4e8f-b97e-9bf08c2fa8fa.png)
![image](https://user-images.githubusercontent.com/120571801/235691054-6d8baf31-55fd-47ac-87aa-70d56cfeb812.png)
![image](https://user-images.githubusercontent.com/120571801/235691089-aa80e595-7390-4b73-9978-51c8af14e8e8.png)

**Comment by Napokue** [comment]
Hi! Thanks for creating this issue, we already received multiple reports about this issue and are actively investigating and working on it.

We have done some troubleshooting with another user already a couple hours ago and got working with a workaround.

Can you try to do the following:

1) Navigate to `%userprofile%\.runelite\collectionlog` (Windows) or `$HOME/.runelite/collectionlog` (MacOs/Linux).
2) Check if there are `json` files located in this folder with the filename: `collectionlog-<your-account-name>.json`.
3) If there is, move it out for now, to "create" a backup.
4) Start the Runelite client.
5) Check a couple of pages to remove the asterisks (`*`).
6) Close the Runelite client.
7) Start the Runelite client and confirm if the asterisks (`*`) are still gone.
5) Check the collection log and go through each page to remove all asterisks (`*`).
6) Upload log to the website and check if the collection log is correct on the website.
7) Either remove the files of step 3 (old collection log file) or keep it without moving it back.

Please let us know if this worked or not.

**Comment by EwwItsMike** [comment]
I've tried these steps and it seems to be updated for now at least. Will give you another update to see if it stays tomorrow morning. Thank you for the reply either way!

**Comment by Napokue** [comment]
Thank you! Great to hear we could temporarily fix it via this workaround.

**Comment by EwwItsMike** [comment]
I forgot to check in the morning, my bad. Log does not seem to have descyned and still has everything in there, so at least the workaround did the job!
Thanks again, closing the issue.
