### ISSUE TITLE
[Investigate] - "Total obtained does not match specific items collected"

### ISSUE THREAD

**Issue by Napokue** [evansloan/collectionlog.net#70]
**What are you experiencing, describe the bug**
Every time the user LiiviD uploads their collection log to the website, the warning: "Total obtained does not match specific items collected" keeps popping up. Investigate why this keeps happening and if there is something we can do about it.

**How are you expecting it would work?**
Not always showing the warning.

**What is your username?**
LiiviD

**Comment by Napokue** [comment]
Issue will be closed, as Good Yard has already answered what the resolution for this is, I quote: "Make sure you click through every page before re-uploading data. Sometimes if you click too fast through the log it won't load the page properly and gets skipped".

**Comment by evansloan** [comment]
Just as a thought, we should probably change the wording of this message to be more clear with what the issue is. "Please re-upload collection log data" isn't very helpful and I think causes some confusion.
