### ISSUE TITLE
Bug with motherlode mine tab

### ISSUE THREAD

**Issue by seforith13** [evansloan/collectionlog.net#71]
**What are you experiencing, describe the bug**
Please provide a clear and concise description so triage will be easier. Provide screenshots of the bug if applicable. 

It shows my collection log as doubled. 

**How are you expecting it would work?**
Please provide a clear and concise description what your expectation is. This provides a better context for the bug.
I expect the motherlode mine collection log to only show 6 as it should. But it instead shows 12. I have the screenshot saved but I do not know how to post it here

**What is your username?**
Please supply your in-game username if applicable.
seforith13 on github and osrs

**Comment by seforith13** [comment]
![2312321312321](https://github.com/evansloan/collectionlog.net/assets/135171037/60a931d9-4bdd-42ae-9366-8858c07bcc06)

**Comment by evansloan** [comment]
This has been fixed

**Comment by seforith13** [comment]
Thank you! Appreciate the hard work!
