### ISSUE TITLE
Feature request - Remove UGIM from GIM HiScores

### ISSUE THREAD

**Issue by MichaelLavin778** [evansloan/collectionlog.net#95]
**Describe the feature**
Remove Unranked Group Irons from the Group Iron collection log HiScores

**What value provides this feature?**
Unranked Group Irons can be irons that have existed for years before any regular Group Iron account, so it doesn't make sense to put them together on the same HiScores with these unfair advantages.

**Additional context**
Unranked Group Irons already have their own HiScores so the only change that would need to be made is just filtering them out of the regular Group Iron HiScores

**Comment by evansloan** [comment]
This is a fair take. Should be fixed now.
